---
# Artifact marking

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import os
import calinet.core.io as cio

In [7]:
marking_file = "Z:\\CALINET2\\converted\\austin\\derivatives\\pspm\\sub-CalinetAustin01\\physio\\sub-CalinetAustin01_task-acquisition_recording-scr_desc-artifacts_physioevents.tsv.gz"

df = cio.read_physio_tsv_headerless(marking_file)
df

         onset   duration trial_type artifact_type channel annotator  message
0    95.145726   8.308603   artifact          crap     scr        GJ      NaN
1   152.639297   0.559746   artifact          crap     scr        GJ      NaN
2   160.195505   3.063940   artifact       unknown     scr        GJ      NaN
3   177.331018   0.658525   artifact          crap     scr        GJ      NaN
4   180.936442   0.460968   artifact          crap     scr        GJ      NaN
5   191.227423   0.050227   artifact          crap     scr        GJ      NaN
6   193.095154   0.035387   artifact          crap     scr        GJ      NaN
7   195.589811   0.373130   artifact          crap     scr        GJ      NaN
8   199.013137  10.904313   artifact       unknown     scr        GJ      NaN
9   214.021472   2.484275   artifact       unknown     scr        GJ      NaN
10  221.785661  10.904313   artifact       unknown     scr        GJ      NaN
11  238.761543  10.904313   artifact       unknown     scr        GJ      NaN
12  297.036499  18.209401   artifact       unknown     scr        GJ      NaN
13  337.884615  17.225109   artifact       unknown     scr        GJ      NaN
14  373.557777  19.208547   artifact       unknown     scr        GJ      NaN

In [26]:
# .mat -> physioevents.tsv.gz converter

from scipy.io import loadmat
from pathlib import Path

mat_path = Path(r"Z:\CALINET2\code\scrf_analysis\derivatives\artefacts")
mat_files = list(mat_path.rglob("*.mat"))

for m in mat_files:
    data = loadmat(m)["epochs"]
    if data.shape[0]>5:
        print(f"{m} contains {data.shape[0]} epochs")
        break

Z:\CALINET2\code\scrf_analysis\derivatives\artefacts\HRM1-2\missing_HRM1-2_wdq_08_sn1.mat contains 7 epochs

In [29]:
from calinet_artifacts.export import mat_to_physioevents_df

df = mat_to_physioevents_df(
    m,
    channel="scr",
    annotator="RP"
)
df

     onset  duration trial_type artifact_type channel annotator message
0   41.180     4.200   artifact      artifact     scr        RP
1   73.130     2.065   artifact      artifact     scr        RP
2  311.480     3.255   artifact      artifact     scr        RP
3  326.270     1.460   artifact      artifact     scr        RP
4  345.075     1.390   artifact      artifact     scr        RP
5  457.585     3.500   artifact      artifact     scr        RP
6  606.840     4.375   artifact      artifact     scr        RP